### PR TITLE
Fixes and slight UI/documentation improvements

### LINKED ISSUE #193: Cookie goals doesn't work
I think, that the cookie goal functionality is broken in current version of `django-experiments`.
I tried that on my project as well as in the example_project - all other goals are recorded, but the cookie not.

I fixed it by adding following code to the `ExperimentsRetentionMiddleware` in middleware.py:
```python
        # record cookie goal
        goal_name = request.COOKIES.get('experiments_goal')
        participant(request).goal(goal_name)
```

### PR DESCRIPTION
**Pull request by PetrDlouhy**
This PR contains #192 and some more edits:
* Some clearings for README
* Clear some things in UI
* Fix #193
* Fix error if request is not set in `confirm_human` templatetag

### CODE REVIEW

File: experiments/static/experiments/js/experiments.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ experiments = function() {
             $.post("/experiments/confirm_human/");
         },
         goal: function(goal_name) {
-            $.post("/experiments/goal/" + goal_name);
+            $.post("/experiments/goal/" + goal_name + "/");
```
Comment (ahmedaljazzar) [inline experiments/static/experiments/js/experiments.js:7]: I think it's cleaner to use f-Strings
```suggestion
            $.post(f"/experiments/goal/{goal_name}/");
```

Comment (PetrDlouhy) [reply experiments/static/experiments/js/experiments.js]: @iamjazzar This is JavaScript 😀. Good try, I attempt, I almost released this.
